### ISSUE TITLE
scaladex for 2.13.0-M3 does not work

### ISSUE THREAD

**Issue by Sciss** [scala/make-release-notes#269]
This document https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md
suggests that

> Scaladex, the index of Scala libraries, now offers searching by target version:
> 
>  -   [All libraries for 2.13.0-M3](https://index.scala-lang.org/search?q=fullScalaVersion%3A2.13.0-M3)

But it does not return any results. Might be a scaladex bug; just wondering whether the idea is still to 

> [edit this page](https://github.com/scala/make-release-notes/edit/2.13.x/projects-2.13.md) and let the world know what libraries are available.

Why not just rely on scaladex (once it works)?

**Comment by SethTisue** [comment]
thanks for calling it to my attention. I hadn't noticed the links didn't work. (they did work at some point in the not too distant past.)

@MasseGuillaume can I ask you to send a PR with working Scaladex links?

> Why not just rely on scaladex (once it works)?

good question.

for me personally, I need to have a place to keep track of how the publishing is going for each milestone, and keeping projects-2.13.md up to date is how I do that. the links to tickets for libraries that haven't published yet is perhaps the most important thing to have, even; Scaladex doesn't have that.

if users find Scaladex more useful than consulting the manually curated list, then great. that's why the Scaladex links are at the top of the page. and after a final release, "just rely on Scaladex" is exactly what we do — we stop updating the list and replace it with Scaladex, as you'll see at https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md

**Comment by MasseGuillaume** [comment]
https://index.scala-lang.org/search?q=fullScalaVersion%3A2.13.0-M3

The original search is lower cased `fullScalaVersion:2.13.0-M3` becomes `fullscalaversion:2.13.0-m3`. It's a regression in scaladex. I think this was to ignore the case when searching for organizations.

**Comment by MasseGuillaume** [comment]
I just redeployed and it works as expected.

**Comment by SethTisue** [comment]
@MasseGuillaume awesome, thanks so much for your attention to this.
